source ~/.alias

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/aeid/.sdkman"
[[ -s "/home/aeid/.sdkman/bin/sdkman-init.sh" ]] && source "/home/aeid/.sdkman/bin/sdkman-init.sh"




