source ~/bin/dotfiles/bash/nogithub 
source ~/bin/dotfiles/bash/alias 
source ~/bin/dotfiles/bash/env

source ~/.bash_profile 

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH
# Path to your oh-my-zsh installation.
export ZSH=/home/aeid/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

plugins=(git , extract , vi-mode , trash , cloudapp)  


source $ZSH/oh-my-zsh.sh



function to-pdf(){
  markdown-pdf -s "~/custom/md.css" $1.md -o $1.pdf 
}

function toPdf(){
  pandoc -f=markdown_github -S -F $1.md -o $1.pdf
}

